NUM_CLIENTS=64
NUM_COUCHBASE_SERVERS_DATA=128
NUM_COUCHBASE_SERVERS_INDEX=1
NUM_COUCHBASE_SERVERS_QUERY=1


CLIENT_INSTANCE_TYPE="c3.xlarge"
COUCHBASE_INSTANCE_TYPE="r3.4xlarge" #c3.8xlarge"

CLIENT_IMAGE="ami-d61d53a1" # libcouchbase with threaded in key
COUCHBASE_IMAGE="ami-31371646" # RC4.0-no-pid-file

