NUM_CLIENTS=2
NUM_COUCHBASE_SERVERS_DATA=4
NUM_COUCHBASE_SERVERS_DATA_NEW=0
NUM_COUCHBASE_SERVERS_INDEX=1
NUM_COUCHBASE_SERVERS_QUERY=1

AVAILABILITY_ZONE="us-east-1a"
CLIENT_INSTANCE_TYPE="c3.xlarge"
COUCHBASE_INSTANCE_TYPE="r3.4xlarge" #c3.8xlarge"

CLIENT_IMAGE="ami-xxxxxxxx"
COUCHBASE_IMAGE="ami-yyyyyyyy"

BUCKET_NAME="aaaaaaaaaaaaaaa"
