---
- hosts: tag_Type_couchbaseserver_data
  remote_user: ubuntu
  serial: 1
  vars:
    couchbase_server_primary_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  connection: local
  tasks:
    - shell: echo {{couchbase_server_primary_node}} > ../../temp_couchbase_server_primary_node


- hosts: tag_Type_couchbaseserver_data:tag_Type_couchbaseserver_query:tag_Type_couchbaseserver_index
  remote_user: ubuntu
  sudo: true
  vars:
    couchbase_server_ubuntu_ee_version: 4.0.0-rc0
    couchbase_server_ubuntu_ee_package: couchbase-server-enterprise-{{ couchbase_server_ubuntu_ee_version }}-ubuntu14.04_amd64.rpm
    couchbase_server_ubuntu_ee_url: http://packages.couchbase.com/releases/{{ couchbase_server_ubuntu_ee_version }}/{{ couchbase_server_ubuntu_ee_package }}

    couchbase_server_admin: Administrator
    couchbase_server_password: couchbase
    couchbase_server_ram: "{{ansible_memtotal_mb|int}}"
    couchbase_server_cluster_ram: "{{(0.2*couchbase_server_ram|int)|int}}"
    couchbase_server_admin_port: 8091
    couchbase_server_home_path: /opt/couchbase/
    couchbase_server_data_path: "/mnt/cbdata"
    couchbase_server_index_path: "/mnt/cbindex"

    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
    couchbase_server_node_type: "{{hostvars[ec2_ip_address]['ec2_tag_Type']}}"
    couchbase_server_bucket_name0: default0
    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_ram: "{{ couchbase_server_cluster_ram |int }}"
    couchbase_server_bucket_port: 11211
    couchbase_server_bucket_replica: 3
    docs_per_node: 25180160

  tasks:
    - name: set couchbase_server_primary_node variable
      set_fact:
        couchbase_server_primary_node: "{{ lookup('file', '../../temp_couchbase_server_primary_node') }}"

    - name: mk filesystem
      shell: mkfs -t ext4 /dev/xvdb

    - name: mount /dev/xvdb
      shell: mount /dev/xvdb /mnt

    - name: chown couchbase:couchbase for /mnt
      shell: chown couchbase:couchbase /mnt

    - name: mkdir cbdata directory
      shell: mkdir -p {{ couchbase_server_data_path }}

    - name: mkdir cbindex directory
      shell: mkdir -p {{ couchbase_server_index_path }}

    - name: chown couchbase:couchbase
      shell: chown couchbase:couchbase {{ couchbase_server_data_path }}

    - name: chown couchbase:couchbase
      shell: chown couchbase:couchbase {{ couchbase_server_index_path }}

    - name: Wait for node to be listening on port 8091
      wait_for: port=8091 delay=30

    - name: Initialize all nodes
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --node-init-hostname={{ couchbase_server_node }} --node-init-data-path={{ couchbase_server_data_path }} --node-init-index-path={{ couchbase_server_index_path }}"

    - name: Configure cluster settings
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --cluster-init-password={{ couchbase_server_password }} --cluster-init-port={{couchbase_server_admin_port}} --cluster-init-ramsize={{ couchbase_server_cluster_ram }} --services=data"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Join additional cluster nodes - data
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} --services=data"
      when: not (couchbase_server_node == couchbase_server_primary_node ) and couchbase_server_node_type == 'couchbaseserver_data'

    - name: Join additional cluster nodes - query
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} --services=query"
      when: couchbase_server_node_type == 'couchbaseserver_query'

    - name: Join additional cluster nodes - index
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} --services=index"
      when: couchbase_server_node_type == 'couchbaseserver_index'

    - name: Rebalance cluster
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Create new default0 bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name0 }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Wait_for directory to exist
      wait_for: path={{ couchbase_server_data_path }}/default0

    - name: Wait for 10 seconds
      pause: seconds=10

    - name: Stop couchbase server
      command: "service couchbase-server stop"

    - name: Run couch_create
      command: "/opt/couchbase/bin/couch_create -k {{ docs_per_node }} --doc-len 1024 -r -l"
      args:
        chdir: "{{ couchbase_server_data_path }}/default0"

    - name: Start couchbase server
      command: "service couchbase-server start"

