---
- hosts: tag_Type_couchbaseserver_data
  remote_user: ubuntu
  serial: 1
  vars:
    couchbase_server_primary_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
    couchbase_server_primary_node_public: "{{hostvars[ec2_ip_address]['ec2_public_dns_name']}}"
  connection: local
  tasks:
    - shell: echo {{couchbase_server_primary_node}} > ../../temp_couchbase_server_primary_node
    - shell: echo {{couchbase_server_primary_node_public}} > ../../temp_couchbase_server_primary_node_public


- hosts: tag_Type_couchbaseserver_data:tag_Type_couchbaseserver_query:tag_Type_couchbaseserver_index
  remote_user: ubuntu
  sudo: true
  vars:
    couchbase_server_ubuntu_ee_version: 4.0.0-rc0
    couchbase_server_ubuntu_ee_package: couchbase-server-enterprise-{{ couchbase_server_ubuntu_ee_version }}-ubuntu14.04_amd64.rpm
    couchbase_server_ubuntu_ee_url: http://packages.couchbase.com/releases/{{ couchbase_server_ubuntu_ee_version }}/{{ couchbase_server_ubuntu_ee_package }}

    couchbase_server_admin: Administrator
    couchbase_server_password: couchbase
    couchbase_server_ram: "{{ansible_memtotal_mb|int}}"
    couchbase_server_cluster_ram: "{{(0.8*couchbase_server_ram|int)|int}}"
    couchbase_server_admin_port: 8091
    couchbase_server_home_path: /opt/couchbase/
    couchbase_server_data_path: "/mnt/cbdata"
    couchbase_server_index_path: "/mnt/cbindex"

    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
    couchbase_server_node_type: "{{hostvars[ec2_ip_address]['ec2_tag_Type']}}"
    couchbase_server_bucket_name0: default0
    couchbase_server_bucket_name1: default1
    couchbase_server_bucket_name2: default2
    couchbase_server_bucket_name3: default3
    couchbase_server_bucket_name4: default4
    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_ram: "{{ (0.1*couchbase_server_cluster_ram|int)|int }}"
    couchbase_server_bucket_port: 11211
    couchbase_server_bucket_replica: 3

  tasks:
    - name: set couchbase_server_primary_node variable
      set_fact:
        couchbase_server_primary_node: "{{ lookup('file', '../../temp_couchbase_server_primary_node') }}"

    - name: mk filesystem
      shell: mkfs -t ext4 /dev/xvdb

    - name: mount /dev/xvdb
      shell: mount /dev/xvdb /mnt

    - name: chown couchbase:couchbase for /mnt
      shell: chown couchbase:couchbase /mnt

    - name: mkdir cbdata directory
      shell: mkdir -p {{ couchbase_server_data_path }}

    - name: mkdir cbindex directory
      shell: mkdir -p {{ couchbase_server_index_path }}

    - name: chown couchbase:couchbase
      shell: chown couchbase:couchbase {{ couchbase_server_data_path }}

    - name: chown couchbase:couchbase
      shell: chown couchbase:couchbase {{ couchbase_server_index_path }}

    - name: Wait for node to be listening on port 8091
      wait_for: port=8091 delay=30

    - name: Initialize all nodes
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --node-init-hostname={{ couchbase_server_node }} --node-init-data-path={{ couchbase_server_data_path }} --node-init-index-path={{ couchbase_server_index_path }}"

    - name: Configure cluster settings
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --cluster-init-password={{ couchbase_server_password }} --cluster-init-port={{couchbase_server_admin_port}} --cluster-init-ramsize={{ ((couchbase_server_ram|int)*0.8)|int }} --services=data"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Join additional cluster nodes - data
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} --services=data"
      when: not (couchbase_server_node == couchbase_server_primary_node ) and couchbase_server_node_type == 'couchbaseserver_data'

    - name: Join additional cluster nodes - query
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} --services=query"
      when: couchbase_server_node_type == 'couchbaseserver_query'

    - name: Join additional cluster nodes - index
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} --services=index"
      when: couchbase_server_node_type == 'couchbaseserver_index'

    - name: Rebalance cluster
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Create new default0 bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name0 }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Create new default1 bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name1 }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Create new default2 bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name2 }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Create new default3 bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name3 }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
      when: couchbase_server_node == couchbase_server_primary_node

    - name: Create new default4 bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name4 }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
      when: couchbase_server_node == couchbase_server_primary_node

- hosts: 127.0.0.1
  connection: local
  tasks:
   - name: set couchbase_server_primary_node_public variable
     set_fact:
       couchbase_server_primary_node_public: "{{ lookup('file', '../../temp_couchbase_server_primary_node_public') }}"

   - name: Add view to default0
     shell: "curl -X PUT -H 'Content-Type: application/json' http://{{ couchbase_server_primary_node_public }}/default0/_design/1 -d @1.ddoc"

   - name: Add view to default1
     shell: "curl -X PUT -H 'Content-Type: application/json' http://{{ couchbase_server_primary_node_public }}/default1/_design/1 -d @1.ddoc"

   - name: Add view to default2
     shell: "curl -X PUT -H 'Content-Type: application/json' http://{{ couchbase_server_primary_node_public }}/default2/_design/1 -d @1.ddoc"

   - name: Add view to default3
     shell: "curl -X PUT -H 'Content-Type: application/json' http://{{ couchbase_server_primary_node_public }}/default3/_design/1 -d @1.ddoc"

   - name: Add view to default4
     shell: "curl -X PUT -H 'Content-Type: application/json' http://{{ couchbase_server_primary_node_public }}/default4/_design/1 -d @1.ddoc"
